/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Extragui;

import javax.swing.ImageIcon;

/**
 *
 * @author lakshay
 */
public class Flash_screen extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Flash_screen
     */
   // Image b;
    public Flash_screen() {
       /* try {
            ImageIcon icons = new ImageIcon(getClass().getResource("/Extragui/new.png"));
            //ImageIcon buts = new ImageIcon(getClass().getResource("/Extragui/butimage.jpg"));
            b = icons.getImage();
        } catch (Exception ex) {
        }*/
        initComponents();
        setIconImage(new ImageIcon("/Extragui/home.png").getImage());
        setSize(370,146);
        setLocationRelativeTo(null);
       // pbar.setStringPainted(true);
       // pbar.setBackground(new Color(153, 204, 255));
        new Thread(this).start();
//        back_ground_label.setIcon(new ImageIcon(b));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back_ground_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(370, 130));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_ground_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extragui/spashscreen.png"))); // NOI18N
        getContentPane().add(back_ground_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 145));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flash_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flash_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_ground_label;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
       int value=0;
       while(true)
       {
           if(value==100)
           {
               break;
           }
           value++;
           //pbar.setValue(value);
           try
           {
               Thread.sleep(10);
           }
           catch(InterruptedException e){
               
           }
       }
       dispose();
      // new Mainframe().setVisible(true);
       logins l = new logins();
    }
}
