/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Extragui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import maingui.Music;

/**
 *
 * @author lakshay
 */
public class logins extends javax.swing.JFrame {

    /**
     * Creates new form logins
     */
    public static Music mu;
    String name1,name2;
    public logins() {
         setIconImage(new ImageIcon("C:\\Users\\lakshay\\Documents\\NetBeansProjects\\gomuku_game\\src\\Extragui/home.png").getImage());
        initComponents();
        setSize(660,220);
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
         mu = new Music();
        mu.playSong(mu.LOGIN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfp2 = new javax.swing.JTextField();
        tfp1 = new javax.swing.JTextField();
        play = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  O");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(610, 70, 34, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  X");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(610, 30, 34, 30);

        tfp2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tfp2);
        tfp2.setBounds(330, 70, 280, 30);

        tfp1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfp1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfp1);
        tfp1.setBounds(330, 30, 280, 30);

        play.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        play.setText("PLAY ! ");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play);
        play.setBounds(465, 140, 180, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Extragui/logins.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 660, 220);
        background.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfp1ActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        if(tfp1.getText().isEmpty()||tfp2.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "one or more fields are empty");
        else
        {
            name1=tfp1.getText().trim();
            name2=tfp2.getText().trim();           
            maingui.Mainframe m = new maingui.Mainframe(name1,name2);
            //m.setN1(name1);
           // m.setN2(name2);
            mu.stop();
            dispose();
        }
    }//GEN-LAST:event_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton play;
    private javax.swing.JTextField tfp1;
    private javax.swing.JTextField tfp2;
    // End of variables declaration//GEN-END:variables
}
